name: build_and_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - run: gem install bundler jekyll

      - run: bundle install

      - name: Run build_and_test.cmd
        run: ./build_and_test.cmd
