name: build_and_test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      - uses: actions/setup-python@v4
      - run: gem install bundler jekyll
      - run: ./build_and_test
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report-${{ matrix.os }}
          path: junit-reports/report.html
