name: build_and_test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1

      - run: gem install bundler jekyll

      - run: ./build_and_test.cmd
